/* Optional UI verification: NODE_PATH must resolve Playwright. No app npm install required. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.DEMO_URL || 'http://127.0.0.1:8000';
const launch = {headless:true};
if(process.env.BROWSER_EXECUTABLE)launch.executablePath=process.env.BROWSER_EXECUTABLE;

(async()=>{
 const browser=await chromium.launch(launch);
 const checks=[];const errors=[];const consoleErrors=[];const requests=[];
 try{
  const context=await browser.newContext({viewport:{width:1440,height:1050}});
  const page=await context.newPage();
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text());});
  page.on('request',r=>requests.push({url:r.url(),method:r.method(),body:r.postData()}));
  const click=async selector=>{await page.locator(selector).first().click();};
  const waitText=async text=>{await page.getByText(text,{exact:true}).waitFor();};
  const waitIdle=async()=>{await page.locator('#reset-button:not([disabled])').waitFor();};
  const reset=async()=>{await click('#reset-button');await waitIdle();await waitText('A deposit plan worth a look.');};
  await page.goto(base);await waitText('Good morning, Sofia.');await reset();
  fs.mkdirSync('artifacts',{recursive:true});
  await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
  await click('[data-action="confirm"]');await waitText('Let’s make room for your move.');
  await click('[data-nav="task"]');await page.locator('[name="rent"]').fill('1100');
  await page.locator('[name="months"]').selectOption('3');await page.locator('[name="moving"]').fill('600');
  await page.getByRole('button',{name:'Update my preview'}).click();await waitIdle();
  await page.getByText('Rental deposit · 3 months',{exact:true}).waitFor();
  for(const item of ['budget','documents','review']){await page.locator(`[data-check="${item}"]`).check();await waitIdle();}
  await page.screenshot({path:'artifacts/planner.png',fullPage:true});
  await click('[data-action="complete"]');await waitText('Your rental deposit plan is ready.');
  checks.push('Sofia: confirm, edit cash-flow inputs, check preparation steps, complete mock task');
  await page.locator('#customer-select').selectOption('thomas');await waitIdle();await reset();
  await click('[data-action="confirm"]');await waitIdle();await click('[data-action="defer"]');await waitText('Your plan can wait.');
  assert.equal(await page.getByText('In-app reminder preview',{exact:true}).count(),0);
  await click('#advance-button');await waitText('Ready when you are.');
  await page.locator('.notice').filter({hasText:'You have a saved task ready to continue.'}).waitFor();
  checks.push('Thomas: saved goal produces no immediate reminder; +7 days reveals generic preview');
  await page.locator('#customer-select').selectOption('emma');await waitIdle();await reset();
  await click('[data-action="dismiss"]');await waitText('Thanks for clearing that up.');
  await click('#advance-button');await waitIdle();await waitText('Thanks for clearing that up.');
  checks.push('Emma: friend correction suppresses suggestions after simulated time advances');
  await page.locator('#customer-select').selectOption('sofia');await waitIdle();await reset();
  await click('[data-view="privacy"]');
  await page.locator('#permission-trends').uncheck();await waitIdle();
  assert(!((await page.locator('#payload-code').textContent()).includes('home-trend')));
  await page.locator('#permission-activity').uncheck();await waitIdle();
  assert.equal((await page.locator('#payload-code').textContent()).trim(),'null');
  checks.push('Permission withdrawal removes revoked facts from actual adapter input');
  await reset();await click('[data-view="privacy"]');
  await page.screenshot({path:'artifacts/privacy.png',fullPage:true});
  await click('[data-view="private"]');
  const frame=page.frameLocator('#private-frame');
  await frame.locator('#private-input').waitFor();
  // Allow static frame assets to finish before measuring conversation traffic.
  const sandboxFrame=page.frames().find(f=>f.url().endsWith('/private.html'));
  await sandboxFrame.waitForFunction(()=>Boolean(document.getElementById('send').onclick));
  const before=requests.length;const canary='CANARY_SYNTHETIC_SECRET_937_FAMILY_REASON';
  await frame.locator('#private-input').fill(canary);
  await frame.getByRole('button',{name:'Try scripted reply'}).click();
  await frame.locator('.message.user').waitFor();
  assert.equal(await frame.locator('.message').count(),3);
  assert.equal(requests.length,before,'Typing and scripted reply must produce zero requests');
  const bank=await page.evaluate(async()=>await(await fetch('/api/state')).text());
  assert(!bank.includes(canary));
  assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
  assert(!fs.readFileSync('data/nextstep.sqlite3').includes(Buffer.from(canary)));
  await page.screenshot({path:'artifacts/private.png',fullPage:true});
  await frame.locator('#clear').click();assert.equal(await frame.locator('.message').count(),1);
  await frame.locator('#consent').check();await frame.locator('#share').click();
  await waitText('Let’s make room for your move.');
  const share=requests.findLast(r=>r.url.endsWith('/api/action/share'));
  assert.deepEqual(JSON.parse(share.body),{statement:'I am planning to move next month.',purpose:'moving_goal_assistance'});
  assert(!requests.some(r=>(r.body||'').includes(canary)||r.url.includes(canary)));
  checks.push('Private canary: zero conversation requests, absent from banking response/database/storage; only approved statement exported');
  await click('[data-view="private"]');
  assert.equal(await page.frameLocator('#private-frame').locator('.message').count(),1);
  await click('[data-view="journey"]');await reset();
  await page.locator('#customer-select').selectOption('noah');await waitIdle();
  await click('#reset-button');await waitIdle();await waitText('Try two bike commutes a week.');
  await page.getByText('15.36 kg CO₂e',{exact:false}).first().waitFor();
  await click('[data-nav="climate"]');await waitText('A smaller trip, on your terms.');
  await page.locator('[data-save-climate="NEARBY_GROCERY"]').click();await waitIdle();
  await page.locator('[data-save-climate="NEARBY_GROCERY"]').getByText('Saved as an idea').waitFor();
  await click('[data-nav="journey"]');
  await page.locator('#ask-input').fill('Why could a bike commute help?');
  await page.getByRole('button',{name:'Ask about this option'}).click();
  await page.locator('#ask-result').getByText('Scripted fallback',{exact:false}).waitFor();
  await page.screenshot({path:'artifacts/v2-climate.png',fullPage:true});
  checks.push('Noah: two code-calculated carbon options, saved idea and clearly labeled follow-up fallback');
  await page.locator('#customer-select').selectOption('sofia');await waitIdle();await reset();
  const mobile=await context.newPage();
  await mobile.setViewportSize({width:390,height:844});
  assert.equal(await mobile.evaluate(()=>window.innerWidth),390);
  await mobile.goto(base);await mobile.getByText('A deposit plan worth a look.',{exact:true}).waitFor();
  assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile must not overflow horizontally');
  await mobile.screenshot({path:'artifacts/mobile.png',fullPage:true});
  await mobile.locator('[data-view="private"]').click();
  await mobile.frameLocator('#private-frame').locator('#private-input').waitFor();
  assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  const privateDoc=mobile.frames().find(f=>f.url().endsWith('/private.html'));
  assert(await privateDoc.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
  await mobile.screenshot({path:'artifacts/mobile-private.png',fullPage:true});
  checks.push('Desktop and 390px mobile layouts; private session clears on leaving');
  assert.deepEqual(errors,[],'No browser runtime errors');
  assert.deepEqual(consoleErrors,[],'No browser console / CSP errors');
  assert(!requests.some(r=>!r.url.startsWith(base)),'No application request to a remote host');
  const evidence={status:'PASS',date:'2026-09-30',browser:await browser.version(),checks,request_count:requests.length,remote_requests:0,private_conversation_requests:0,runtime_errors:errors,console_errors:consoleErrors,limits:'Browser request observation covers these scripted UI paths only. Not a machine-wide packet capture or real local-model privacy verification.'};
  fs.writeFileSync('artifacts/browser-validation.json',JSON.stringify(evidence,null,2));
  console.log(JSON.stringify(evidence,null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
